#!/usr/bin/bash
# GNU Affero General Public License v3.0 or later (see COPYING or https://www.gnu.org/licenses/agpl.txt)
# https://www.shellcheck.net/wiki/SC2139: single quotes are used intentionally

alias cp='cp --interactive'
alias grep='grep --color=auto'
alias ll='ls --almost-all --color=auto --human-readable --format=long --indicator-style=slash --time-style=long-iso'
alias mkdir='mkdir --verbose --parents'
alias mv='mv --interactive'
alias rm='rm --interactive --preserve-root'
alias rsync='rsync --human-readable --progress --recursive --links --perms --times --owner --group'
alias watch='watch --color --differences --interval=1 --precise --exec'

alias yt_audio='yt-dlp --config-location ${HOME}/.config/yt-dlp-audio.conf'

alias gd='git diff'
alias gs='git status --short'
alias gsa='for _ in $(find $(pwd) -maxdepth 1 -mindepth 1 -type d); do echo $_ && git -C $_ status --short; done'
alias ga='git add'
alias gcm='git commit -m'
alias gp='git push'

